spring.application.name=HealthManagement

# Database Config (Injected via Environment Variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Migration Setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}

# Google AI (Uncomment these lines when you are ready to use Gemini features)
# spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# spring.ai.google.genai.chat.options.model=gemini-2.5-flash
# spring.ai.google.genai.chat.options.temperature=0.7

# Security Config (JWT)
jwt.secret=${JWT_SECRET}
jwt.expiration=18000000

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect