spring.application.name=HealthManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/patientmanagement
spring.datasource.username=dominic
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=dominic
spring.flyway.password=1234

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7


jwt.secret=replace-this-with-a-long-random-base64-secret-at-least-256-bits
jwt.expiration=18000000